# Generated by Django 4.2.5 on 2023-09-27 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('caption', models.CharField(max_length=25)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'post_content',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('add_Like', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialBook.postcontent')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('add_comment', models.CharField(max_length=25)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialBook.postcontent')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
