# Generated by Django 4.2.5 on 2023-09-27 18:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('caption', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialBook.upload'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialBook.upload'),
        ),
        migrations.DeleteModel(
            name='PostContent',
        ),
    ]
