# Generated by Django 4.2.5 on 2023-09-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_name_alter_user_password'),
        ('socialBook', '0002_upload_alter_comment_post_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to='user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_comment',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_post', to='socialBook.upload'),
        ),
        migrations.AlterField(
            model_name='like',
            name='add_Like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='socialBook.upload'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='caption',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
