# Generated by Django 4.2.5 on 2023-09-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_name_alter_user_password'),
        ('socialBook', '0003_upload_user_alter_comment_add_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='user.user'),
        ),
    ]
